<?php ini_set('display_errors', 1); error_reporting(E_ALL);
    require_once("includes/functions.php");
   // confirm_logged_in();    $errors = array();    include("includes/header.php");
    $servername = "localhost";    $username = "mnvbcou1_mike";    $password = "KaiSkye14";    $dbname = "mnvbcou1_musiccafe";
    $conn = new mysqli( $servername, $username, $password, $dbname );    if( $conn->connect_error ) {        die( $debugmode ? "Connection failed: " . $conn->connect_error : 'Unable to connect to database' );    } 
	$points = $date = $day = $start_time = $host = $number_of_players = $fp_name = $fp_email = $sp_name = $sp_email = "";
	// Explode the string at the end of each line,	// array map and remove any special chars then trim white space.
	$records = explode( PHP_EOL, $_POST['points'] );    $records = array_map('htmlspecialchars', $records );	$records = array_map ('trim', $records);
// now each line of the NJ's report is in an array, call the array $records[index number]// use substr( ,  , ) to find the needed part of the array indexs,// I.E in the array $records on line 2  is the Date the actual needed information is the date dd/mm/yyyy,// so we use $date = substr($records[2], 7, 10); // from this string : Date:  01/18/2017 which is line 2 in records we get the 01/18/2017 
	// Get Date	$date = substr($records[2], 7, 10);	echo "<b>Tournament Date: </b>" . $date . "<br />";	// Get star time	$start_time = substr($records[4], 18, 7);	echo "<b>Tournament Start Time: </b>" . $start_time . "<br />";
	// get Host name	$host = substr($records[7], 7);	echo "<b>Tournament Host: </b>" . $host . "<br />";
	// get number of players 	$number_of_players = substr($records[8], 20);	echo "<b> Number Of Players: </b>" . $number_of_players . "<br />";	echo "<br />";
	// get the first place name and email address	$fplaceName = substr($records[10], 12);	echo "<b>1ST place: </b>" . $fplaceName . "<br />";	$fplaceEmail = substr($records[11], 18);	echo "<b>1ST place Email: </b>" . $fplaceEmail . "<br />";	// Get second place name and email	$splaceName = substr($records[12], 12);	echo "<b>2ND place Email: </b>" . $splaceName . "<br />";	$splaceEmail = substr($records[13], 18);	echo "<b>2ND place Email: </b>" . $splaceEmail . "<br />";
	// get third place name and email	$tplaceName = substr($records[14], 12);	echo "<b>3RD place Email: </b>" . $tplaceName . "<br />";	$tplaceEmail = substr($records[15], 18);	$t1placeEmail = "fake@fake.com";	if($tplaceEmail == "") { // if third place email is empty add a generic fake email else continue as normal		$tplaceEmail = $t1placeEmail;	} ;	echo "<b>3RD place Email: </b>" . $tplaceEmail . "<br />";
	// if there is a second 3rd place insert into toc_invites.	if(substr($records[16], 0, 1) == '3') {		// get 4th place name and email.		$fthplaceName = substr($records[16], 12);	echo "<b>3RD place Email: </b>" . $fthplaceName . "<br />";	$fthplaceEmail = substr($records[17], 18);	$fth1placeEmail = "fake@fake.com";	if($fthplaceEmail == "") { // if third place email is empty add a generic fake email else continue as normal		$fthplaceEmail = $fth1placeEmail;	} ;	echo "<b>3RD place Email: </b>" . $fthplaceEmail . "<br />";	echo "<hr /><br /><br />";		// Getting the players and points.		$parts1 = array_slice($records, 20, -1);		$end = array_pop($parts1);		$records = array_map('htmlspecialchars', $records );		$records = array_map ('trim', $records);		foreach( $parts1 as $record ) {        $lastSpace = strrpos( $record, ' ' );        $player = trim( substr( $record, 0, $lastSpace ) );        $points = trim( substr( $record, $lastSpace+1 ) );	
// $sql to INSERT INTO bg_points  the player names and points        $sql = "insert into `bg_points` (`player_name`, `points`) values (?, ?)                on duplicate key update points = points + ?";        $stmt = $conn->prepare( $sql );        if( $stmt ){            $stmt->bind_param( 'sss', $player, $points, $points );            $result = $stmt->execute();        }		   echo "Player Name: '{$player}', Points: {$points}<br>\n";    }	// END SQL INSERT INTO bg_points
		// toc_invites INSERT codes		// Player 1 codes		$stmt1 = $conn->prepare("INSERT INTO toc_invites (play, email) VALUES (?,?)");		$stmt1->bind_param("ss", $fplaceName, $fplaceEmail);		$stmt1->execute();
		// player 2 codes		$stmt1->bind_param("ss", $splaceName, $splaceEmail);		$stmt1->execute();
		// player 3 codes		$stmt1->bind_param("ss", $tplaceName, $tplaceEmail);		$stmt1->execute();
		// if(!empty()); INSERT fourth place name and email.
		if(!empty($fthplaceName && $fthplaceEmail )) {			$stmt1->bind_param("ss", $fthplaceName, $fthplaceEmail);				$stmt1->execute();		}	// End of player name and email INSERT INTO 'toc_invites'
		// Start the tournament_data INSERT.		$stmt1 = $conn->prepare("INSERT INTO `tournament_data` (`date`, `start_time`, `host`, `number_of_players`) VALUES (?, ?, ?, ?)");		$stmt1->bind_param("ssss", $date, $start_time, $host, $number_of_players);		$stmt1->execute();
//    include("includes/footer.php");    $conn->close();	} else { // we don't have a second 3rd place so change line index in records to get points.		echo "<hr /><br /><br />";
	// Getting the players and points.		$parts1 = array_slice($records, 18, -1);		$end = array_pop($parts1);		$records = array_map('htmlspecialchars', $records );		$records = array_map ('trim', $records);		foreach( $parts1 as $record ) {        $lastSpace = strrpos( $record, ' ' );        $player = trim( substr( $record, 0, $lastSpace ) );        $points = trim( substr( $record, $lastSpace+1 ) );
// $sql to INSERT INTO bg_points  the player names and points        $sql = "insert into `bg_points` (`player_name`, `points`) values (?, ?)                on duplicate key update points = points + ?";        $stmt = $conn->prepare( $sql );        if( $stmt ){            $stmt->bind_param( 'sss', $player, $points, $points );            $result = $stmt->execute();        }		   echo "Player Name: '{$player}', Points: {$points}<br>\n";    }	// END SQL INSERT INTO bg_points
		// toc_invites INSERT codes		// Player 1 codes		$stmt1 = $conn->prepare("INSERT INTO toc_invites (play, email) VALUES (?,?)");		$stmt1->bind_param("ss", $fplaceName, $fplaceEmail);		$stmt1->execute();
		// player 2 codes		$stmt1->bind_param("ss", $splaceName, $splaceEmail);		$stmt1->execute();
		// player 3 codes		$stmt1->bind_param("ss", $tplaceName, $tplaceEmail);		$stmt1->execute();	// End of player name and email INSERT INTO 'toc_invites'
		// Start the tournament_data INSERT.		$stmt1 = $conn->prepare("INSERT INTO tournament_data (date, start_time, host, number_of_players) VALUES (?,?, ?, ?)");		$stmt1->bind_param("ssss", $date, $start_time, $host, $number_of_players);		$stmt1->execute();
		//    include("includes/footer.php");    $conn->close();	}	?>